### PR TITLE
Fixing deprecation warnings for Rails 4.2

### PR DESCRIPTION
**Pull request by kiddrew**
Just noticed that upgrading to Rails 4.2 produces a bunch of deprecation warnings for this gem.  Quick fix.

### CODE REVIEW

**Comment by adisos** [comment]
+1

**Comment by biow0lf** [comment]
:+1:

**Comment by Fedcomp** [comment]
+1

**Comment by tricknotes** [comment]
:+1: for me.
@mfairburn :+1:  / :-1: ?

**Pull request merged**
